雑に node_modules をアップロードすればいい説を見たけど無理だった
```
Run ./.github/actions/parse-frontmatter
  with:
    content: Hey
node:internal/modules/cjs/loader:488
      throw e;
      ^

Error: Cannot find module '/home/runner/work/timely-issue-posting/timely-issue-posting/node_modules/uuid/dist/index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/timely-issue-posting/timely-issue-posting/node_modules/@actions/core/lib/file-command.js:28:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/runner/work/timely-issue-posting/timely-issue-posting/node_modules/uuid/package.json'
```